export const MARKER_ADDITION_STARTED = 'MARKER_ADDITION_STARTED'
export const MARKER_ADDITION_COMPLETED = 'MARKER_ADDITION_COMPLETED'
export const MARKER_ADDITION_FAILED = 'MARKER_ADDITION_FAILED'

export const MARKERS_FETCHING_STARTED = 'MARKERS_FETCHING_STARTED'
export const MARKERS_FETCHING_COMPLETED = 'MARKERS_FETCHING_COMPLETED'
export const MARKERS_FETCHING_FAILED = 'MARKERS_FETCHING_FAILED'