export const CREATE_MAP_STARTED = 'CREATE_MAP_STARTED';
export const CREATE_MAP_COMPLETED = 'CREATE_MAP_COMPLETED';
export const CREATE_MAP_FAILED = 'CREATE_MAP_FAILED';

export const FETCH_MAP_STARTED = 'FETCH_MAP_STARTED';
export const FETCH_MAP_COMPLETED = 'FETCH_MAP_COMPLETED';
export const FETCH_MAP_FAILED = 'FETCH_MAP_FAILED';


