export const CREATE_MAP_STARTED = 'CREATE_MAP_STARTED';
export const CREATE_MAP_COMPLETED = 'CREATE_MAP_COMPLETED';
export const CREATE_MAP_FAILED = 'CREATE_MAP_FAILED';

export const FETCH_MAP_STARTED = 'FETCH_MAP_STARTED';
export const FETCH_MAP_COMPLETED = 'FETCH_MAP_COMPLETED';
export const FETCH_MAP_FAILED = 'FETCH_MAP_FAILED';

export const DELETE_MAP_STARTED = 'DELETE_MAP_STARTED';
export const DELETE_MAP_COMPLETED = 'DELETE_MAP_COMPLETED';
export const DELETE_MAP_FAILED = 'DELETE_MAP_FAILED';

export const UPDATE_MAP_STARTED = 'UPDATE_MAP_STARTED';
export const UPDATE_MAP_COMPLETED = 'UPDATE_MAP_COMPLETED';
export const UPDATE_MAP_FAILED = 'UPDATE_MAP_FAILED';   

export const SELECT_MAP = 'SELECT_MAP';
