export const CREATE_MAP_STARTED = 'CREATE_MAP_STARTED';
export const CREATE_MAP_COMPLETED = 'CREATE_MAP_COMPLETED';
export const CREATE_MAP_FAILED = 'CREATE_MAP_FAILED';

export const FETCH_MAP_STARTED = 'FETCH_MAP_STARTED';
export const FETCH_MAP_COMPLETED = 'FETCH_MAP_COMPLETED';
export const FETCH_MAP_FAILED = 'FETCH_MAP_FAILED';

export const REMOVE_MAP_STARTED = 'REMOVE0_MAP_STARTED';
export const REMOVE_MAP_COMPLETED = 'REMOVE0_MAP_COMPLETED';
export const REMOVE_MAP_FAILED = 'REMOVE0_MAP_FAILED';
