export const FETCH_QR_DATA_STARTED = "FETCH_QR_DATA_STARTED";
export const FETCH_QR_DATA_COMPLETED = "FETCH_QR_DATA_COMPLETED";
export const FETCH_QR_DATA_FAILED = "FETCH_QR_DATA_FAILED";

export const UPDATE_NODES_STARTED = 'UPDATE_NODES_STARTED';
export const UPDATE_NODES_COMPLETED = 'UPDATE_NODES_COMPLETED';
export const UPDATE_NODES_FAILED = 'UPDATE_NODES_FAILED';