export const FETCH_ERROR_DATA_STARTED = "FETCH_ERROR_DATA_STARTED";
export const FETCH_ERROR_DATA_COMPLETED = "FETCH_ERROR_DATA_COMPLETED";
export const FETCH_ERROR_DATA_FAILED = "FETCH_ERROR_DATA_FAILED";
